# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - '*'

variables:
- name: BuildPlatform
  value:  'any cpu'
- name: BuildConfiguration
  value: 'release'

stages:
- stage: create_policies
  displayName: 'Create the policies'
  #condition: and(always(), eq(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: create_policies_on_azure
    #variables:
    #- group: feature-simplehttpapiapp
    displayName: 'Job: Create policies on Azure'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: Management Group
        azureResourceManagerConnection: "policy-deploy1"
        location: North Europe
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/policies/webappskus/policydef.json
        deploymentMode: 'Incremental'
      displayName: 'Create Policy Definition'